apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: docker.io/asbjoern09/simple-fortune-cookie-backend:latest
          name: backend
          ports:
            - containerPort: 9000
          resources: {}
          envFrom:
            - configMapRef:
                name: redis-config
            - secretRef:
                name: redis-secret
                  
