FROM golang:1.20-alpine as build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /fortune-app
FROM alpine:latest
WORKDIR /root/
COPY --from=build /fortune-app .
EXPOSE 9000
CMD ["./fortune-app"]
