apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-staging
  name: backend-staging
spec:
  ports:
    - port: 9002
      protocol: TCP
      targetPort: 9000
  selector:
    app: backend-staging
  type: ClusterIP