apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-staging
  name: frontend-staging
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend-staging
  type: NodePort