apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-staging
  name: frontend-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-staging
  template:
    metadata:
      labels:
        app: frontend-staging
    spec:
      containers:
        - image: docker.io/asbjoern09/simple-fortune-cookie-frontend:staging
          name: frontend-staging
          env:
          - name: BACKEND_PORT
            value: "9002"
          - name: BACKEND_DNS
            value: backend-staging

