apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-staging
  name: redis-staging
spec:
  ports:
    - port: 6381
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-staging
  type: ClusterIP
