apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-staging
  name: redis-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-staging
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-staging
    spec:
      volumes:
        - name: redis-pvc 
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
        - image: docker.io/library/redis:7.0
          name: redis-staging
          ports:
            - containerPort: 6379
          resources: {}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
              subPath: redis
status: {}
