# This pipeline deploys runs on main, development and staging branches, it builds, tests, uplodas docker image to docker hub and deploys to kubernetes
name: Deployment pipeline
on:
  push:
    branches:
      - main
      - development
      - staging
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}
  BRANCH_NAME: ${{ github.ref_name }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build backend
        run: |
          cd backend
          go build
      - name: Build frontend
        run: |
          cd frontend
          go build
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: run linting
        uses: super-linter/super-linter/slim@v5 
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true 
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run frontend test
        working-directory: frontend
        run: go test 
  Docker-image-backend:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
    - name: Download code
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: ls
      run: ls -la CI-scripts
    - name: build docker
      env:
        DIRECTORY: backend/
        IMAGE: backend
      run: bash CI-scripts/build-docker.sh
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
    - name: Scan Docker image with Trivy
      env:
        IMAGE: backend
      run: trivy image --exit-code 1 --severity HIGH,CRITICAL docker.io/$docker_username/simple-fortune-cookie-${IMAGE}:${BRANCH_NAME}
      continue-on-error: true
    - name: push docker
      env:
        IMAGE: backend
      run: bash CI-scripts/push-docker.sh
  Docker-image-frontend:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
    - name: Download code
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: ls
      run: ls -la CI-scripts
    - name: build docker
      env:
        DIRECTORY: frontend/
        IMAGE: frontend
      run: bash CI-scripts/build-docker.sh
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
    - name: Scan Docker image with Trivy
      env:
        IMAGE: frontend
      run: trivy image --exit-code 1 --severity HIGH,CRITICAL docker.io/$docker_username/simple-fortune-cookie-${IMAGE}:${BRANCH_NAME}
      continue-on-error: true
    - name: push docker
      env:
        IMAGE: frontend
      run: bash CI-scripts/push-docker.sh
  Deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [Docker-image-frontend, Docker-image-backend]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      - name: Run deployment script
        run: bash CI-scripts/deploy.sh
      - name: Run functional test
        run: bash CI-scripts/test-application.sh
        
  # If the tests pass, it can be rebased to staging.
  Rebase-to-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [Deployment]
    if: github.ref_name == 'development' && needs.Deployment.result == 'success'
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
        
      - name: Checkout staging branch
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0

      - name: Set Git identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "Github Actions"

      - name: Rebase staging onto development
        run: git rebase origin/development

      - name: Push changes to staging
        run: git push --force origin staging
