name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build backend
        run: |
          cd backend
          go build
      - name: Build frontend
        run: |
          cd frontend
          go build
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Run frontend test
        working-directory: frontend
        run: go test 
        
        
