name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  docker_username: asbjoern09
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build backend
        run: |
          cd backend
          go build
      - name: Build frontend
        run: |
          cd frontend
          go build
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run frontend test
        working-directory: frontend
        run: go test 
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
    - name: Download code
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: ls
      run: ls -la CI-scripts
    - name: build docker
      run: bash CI-scripts/build-docker.sh
    - name: push docker
      run: bash CI-scripts/push-docker.sh
        
        
